apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: exo-webtest
  name: exo-webtest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: exo-webtest
  template:
    metadata:
      labels:
        app: exo-webtest
    spec:
      containers:
      - image: ghcr.io/exoscale-labs/exo-webtest
        name: exo-webtest
